language: scala
dist: trusty
scala:
  - 2.12.8
jdk:
  - oraclejdk8
script: sbt ++$TRAVIS_SCALA_VERSION clean test
notifications:
  slack: thenewmotion:AXSluctig1mmZbeKRDeeY41s
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
